my_prototype/dictionary/urls.py
from django.urls import path
from . import views

app_name = 'dictionary'

urlpatterns = [
    path('', views.home_view, name = 'home'), 
    path('view_1/', views.view_1, name = 'view_1'), 
    # path('<int:id>/', views.sub_view_2, name = 'view_2'),
    # path('<int:id>/', views.sub_view_3, name = 'view_3'),
]

my_prototype/my_prototype/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dictionary.urls')),
    
]

my_prototype/dictionary/models.py
from django.db import models

# Create your models here.

class Word(models.Model): 
    e_word = models.CharField(max_length = 30)

    def __str__(self): 
        return self.e_word

my_prototype/dictionary/views.py
from django.shortcuts import render
from django.http import Http404
from .models import Word 
from easygoogletranslate import EasyGoogleTranslate

# Create your views here.

def home_view(request):
    return render(request, 'dictionary/base.html')

def view_1(request):
    # try: 
    #     e_word = Word.objects.get(id = id)
    # except Word.DoesNotExist: 
    #     raise Http404("Not found.")
    # translator = EasyGoogleTranslate()
    # result = translator.translate(e_word, target_language='vi')

    return render(request, 'dictionary/view_1.html' )

def sub_view_2(request):
    # try: 
    #     e_word = Word.objects.get(e_word = e_word)
    # except Word.DoesNotExist: 
    #     raise Http404("Not found.")
    # translator = EasyGoogleTranslate()
    # result = translator.translate(e_word, target_language='fr')

    return render(request, 'dictionary/view_2.html')


def sub_view_3(request):
    # try: 
    #     e_word = Word.objects.get(e_word = e_word)
    # except Word.DoesNotExist: 
    #     raise Http404("Not found.")
    # translator = EasyGoogleTranslate()
    # result = translator.translate(e_word, target_language='tr')

    return render(request, 'dictionary/view_3.html')

my_prototype/dictionary/templates/dictionary/base.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'styles\testingRandomThings.css' %}">
    <title>fucking kill me <3 </title>
  </head>

  <body>

    <!-- 
      Navbar
    -->
    <nav class="navbar navbar-expand-lg navbar-dark flex-md-row bd-navbar">

      <!-- 
        Homepage link
       -->
      <a class="navbar-brand align-items-center" href="{% url 'dictionary:view_1' %}" >
        <img src="{% static 'images\logo.png' %}" class="rounded img-fluid col-sm rounded mx-auto logo-image" alt="Responsive image" >
        Tốn Liền's super pretty web
      </a>

      
      <!-- 
        Responsive button for when the window size get small
       -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- 
        Other buttons to lead to other URLs
       -->
      <div class="collapse navbar-collapse align-content-center" id="navbarNav">
        <ul class="navbar-nav ">
          <!-- 
            Home button
           -->
          <li class="nav-item active ">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <!-- 
            Feature button
           -->
          <li class="nav-item ">
            <a class="nav-link" href="#feature">Features</a>
          </li>
        </ul>

        <!-- 
          Log out button
         -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Log out</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <!-- 
      Little cute dog at the bottom
     -->
    <a href = "https://youtu.be/3NeMPxB37B4" class="hehe">
      <img src="{% static 'images\dog.gif' %}" class="fixed-bottom-left front-layer moving-image dog-image" alt="doggo swimming">
    </a>
    
    <!-- Welcome text - Currently left blank -->
    {% comment %} <div class="welcome-text text-left" >
    </div> {% endcomment %}


    <div class="welcome-text-outer">
      <!-- 
        Column 3
       -->
        <div class="p-3 welcome-settings welcome-text-outer" >

          <h1 class="text-center welcome-text">ANGLaiS</h1>
          <p class="text-center sub-welcome-text"> Free language learning service </p>
        </div>
    </div>
    <!-- 
      3 Columns for 3 functionalities
     -->
    
    <div class="row justify-content-between px-5 outer_column">
      <div class="col-sm mx-auto screen_side_separator">
        <!-- 
          Column 1
         -->
        <div class="p-3 column-settings " id="feature">
          <!-- Column 1 - image -->
          <img src="{% static 'images\logo.png' %}" class="rounded img-fluid rounded mx-auto d-block" alt="Responsive image" >
          <!-- Column 1 - text -->
          <p class="text-center">One of three columns</p>
        </div>
      </div>
      <div class="col-sm mx-auto screen_side_separator">
        <!-- 
          Column 2
         -->
        <div class="p-3 column-settings" >
          <img src="{% static 'images\logo.png' %}" class="rounded img-fluid rounded mx-auto d-block" alt="Responsive image" >
          <p class="text-center">One of three columns</p>
        </div>
      </div>
      <div class="col-sm mx-auto screen_side_separator" >
        <!-- 
          Column 3
         -->
        <a class="text-center overall_div no-underline" href = "{% url 'dictionary:view_1' %}" >
          <div class="p-3 column-settings" >
            <img src="{% static 'images\logo.png' %}" class="rounded img-fluid rounded mx-auto d-block" alt="Responsive image"  >
            <p class="text-center">One of three columns</p>
          </div>
        </a>
      </div>
      
    </div>

    <!-- 
      Column 3
      -->
      <div class="p-3 end-settings" >

        <h1 class="end-text">Contact us</h1>
        <p class="sub-end-text">facebook: Dumamay</p>
        <p class="sub-end-text">Instagram: Cailonma</p>
        <p class="sub-end-text">Youtube: TonLien</p>
        <p class="sub-end-text">contactcailonay</p>
      </div>
    
    

    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

my_prototype/dictionary/templates/dictionary/view_1.html
{% load bootstrap4 %}
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'styles\func_1_styles.css' %}">
    <title>fucking kill me <3 </title>
  </head>

  <body>

    <!-- 
      Navbar
    -->
    <nav class="navbar navbar-expand-lg navbar-dark flex-md-row bd-navbar">

      <!-- 
        Homepage link
       -->
      <a class="navbar-brand align-items-center" href="{% url 'dictionary:view_1' %}" >
        <img src="{% static 'images\logo.png' %}" class="rounded img-fluid col-sm rounded mx-auto logo-image" alt="Responsive image" >
        Tốn Liền's super pretty web
      </a>

      
      <!-- 
        Responsive button for when the window size get small
       -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- 
        Other buttons to lead to other URLs
       -->
      <div class="collapse navbar-collapse align-content-center" id="navbarNav">
        <ul class="navbar-nav ">
          <!-- 
            Home button
           -->
          <li class="nav-item active ">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <!-- 
            Feature button
           -->
          <li class="nav-item ">
            <a class="nav-link" href="#">Features</a>
          </li>
        </ul>

        <!-- 
          Log out button
         -->
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#">Log out</a>
          </li>
        </ul>
      </div>
    </nav>
    
    <!-- Welcome text - Currently left blank -->
    <div class="welcome-text text-left" >
    </div>

    <div class = "set_declarer">
      <div class = "set_container">
        <div class = "set_name_container">
          <input class = "set_name" type="text" placeholder="Set name">
        </div>
        <div class = "desc_name_container">
          <input class = "desc_name" type="text" placeholder="Desc">
        </div>
      </div>
    </div>

    <div class="set_creator">
      <div class="inputFieldContainer">

        <div class = "drop_1_container">
          <select class = "drop_1">
            <option value="Field1">Field 1</option>
            <option value="Field2">Field 2</option>
            <option value="Field3">Field 3</option>
            <option value="Field4">Field 4</option>
          </select>          
        </div>
        <div class="word-container">
          <input class="word" type="text" placeholder="Word">        
        </div>
        <div class="translation-container">
          <input class="translation" type="text" placeholder="Translation">        
        </div>
        <div class = "drop_2_container">
          <select class = "drop_2">
            <option value="Field1">Field 1</option>
            <option value="Field2">Field 2</option>
            <option value="Field3">Field 3</option>
            <option value="Field4">Field 4</option>
          </select>          
        </div>

      </div>
    </div>

    

    

    <div class = "button_declarer">
      <div class = "button_container">
        <div class = "add_more_container">
          <button class = "add_more" onclick="addInputFields()">Add Field</button>
        </div>
        <div class = "confirm_set_container">
          <button class = "confirm_set" onclick="">Confirm set</button>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="../../static/js/func_1.js"></script>


  </body>
</html>

my_prototype/dictionary/templates/dictionary/view_2.html
<h1>Hello</h1>

my_prototype/dictionary/templates/dictionary/view_3.html
<h1>Hello</h1>